#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase

loseCases="../pitzDaily-stepFunction"
for caseName in $loseCases
do
    removeCase $caseName
done

#------------------------------------------------------------------------------
