#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runApplication makeFaMesh -allAreas

runApplication decomposePar -allAreas

runParallel $(getApplication)

runApplication reconstructPar -allAreas

#------------------------------------------------------------------------------
