#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cp -rf \
    "$FOAM_TUTORIALS"/resources/geometry/rotorDisk \
    constant/triSurface

runApplication surfaceTransformPoints -rotate-angle '((1 0 0) 5)' \
    "$FOAM_TUTORIALS"/resources/geometry/rotorDisk/rotatingZone.obj \
    constant/triSurface/rotatingZone.obj

restore0Dir

runApplication blockMesh

runApplication surfaceFeatureExtract

runApplication topoSet

runApplication surfaceMeshExtract -featureAngle 45 -patches '(ZZZZZZ)' \
    -faceZones '(movingZone)' -extractZonePoints constant/triSurface/dummy.obj

foamDictionary constant/dynamicMeshDict -entry dynamicFvMesh \
    -set dynamicMotionSolverFvMesh
foamDictionary system/controlDict -entry stopAt -set writeNow

runApplication moveDynamicMesh -overwrite

rm -rf constant/polyMesh/{sets,faceZones,pointMesh} 1

foamDictionary constant/dynamicMeshDict -entry dynamicFvMesh -set staticFvMesh
foamDictionary system/controlDict -entry stopAt -set endTime

runApplication snappyHexMesh -overwrite

runApplication $(getApplication)

#------------------------------------------------------------------------------
