#!/bin/sh
cd "${0%/*}" || exit 1

. "${WM_PROJECT_DIR:?}/bin/tools/RunFunctions"

nProcs="$(foamDictionary system/decomposeParDict -entry numberOfSubdomains -value)"

blockMesh	2>&1 | tee log.blockMesh
checkMesh	2>&1 | tee log.checkMesh

decomposePar -lib '(libfaradaicBCs.so)'	2>&1 | tee log.decomposePar

mpirun -np "$nProcs" \
"$FOAM_USER_APPBIN/pimpleFoamReact" \
-parallel \
-lib '(libfaradaicBCs.so)' \
2>&1 | tee log.pimpleFoamReact

reconstructPar 2>&1 | tee log.reconstructPar
